export const XboxKeys = {
    A: 0,
    B: 1,
    X: 2,
    Y: 3,
    LB: 4,
    RB: 5,
    LT: 6, 
    RT: 7,
    Menu: 8,
    View: 9,
    LS: 10,
    RS: 11,
    Up: 12,
    Down: 13,
    Left: 14,
    Right: 15,
    AxelLeftHorizontal: 0,
    AxelLeftVertical: 1,
    AxelRightHorizontal: 2,
    AxelRightVertical: 3,
}